version: '3.1'

services:
  application-portal-web:
    image: nginx
    container_name: application-portal-web
    ports:
      - 8080:80
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  # application-portal-server:
  #   build:
  #     context: ../server
  #     dockerfile: Dockerfile
  #   container_name: application-portal-server
  #   ports:
  #     - 8000:8000
